<h4>Categories</h4>
<ul>
    <li><a href="#">Foo</a></li>
    <li><a href="#">Bar</a></li>
    <li><a href="#">Baz</a></li>
    <li>
        <ul>
            <li><a href="#">Qux</a></li>
            <li><a href="#">Quux</a></li>
        </ul>
    </li>
    <li><a href="#">Corge</a></li>
    <li><a href="#">Grault</a></li>
    <li><a href="#">Garply</a></li>
</ul>
<h4>Archives</h4>
<ul>
    <li><a href="#">September 08</a></li>
    <li><a href="#">August 08</a></li>
    <li><a href="#">July 08</a></li>
    <li><a href="#">June 08</a></li>
    <li><a href="#">May 08</a></li>
    <li><a href="#">April 08</a></li>
    <li><a href="#">March 08</a></li>
</ul>