<div class="featurebox">
    <h3>About This Blog</h3>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam porttitor
        suscipit mauris.</p><p>Ut ornare, enim at pulvinar fringilla, dolor ligula 
        malesuada leo, vitae volutpat neque augue nec turpis.</p>
</div>
<div class="featurebox">
    <h3>Categories</h3>
    <ul>
        <li><a href="#">Foo</a></li>
        <li><a href="#">Bar</a></li>
        <li><a href="#">Baz</a></li>
        <li>
            <ul>
                <li><a href="#">Qux</a></li>
                <li><a href="#">Quux</a></li>
            </ul>
        </li>
        <li><a href="#">Corge</a></li>
        <li><a href="#">Grault</a></li>
        <li><a href="#">Garply</a></li>
    </ul>
</div>
<div class="featurebox">
    <h3>Archives</h3>
    <ul>
        <li><a href="#">September 08</a></li>
        <li><a href="#">August 08</a></li>
        <li><a href="#">July 08</a></li>
        <li><a href="#">June 08</a></li>
        <li><a href="#">May 08</a></li>
        <li><a href="#">April 08</a></li>
        <li><a href="#">March 08</a></li>
    </ul>
</div>