<h2>Contact</h2>
<form action="" method="post" class="f-wrap-1">
<fieldset>
    <h3>Contact Me</h3>
    <label for="name"><b>Name: </b><input type="text" id="name" name="name" /><br /></label>
    <label for="email"><b>Email address: </b><input type="text" id="email" name="email" /><br /></label>
    <label for="subject"><b>Subject: </b><input type="text" id="subject" name="subject" /><br /></label>
    <label for="message"><b>Message: </b><textarea id="message" name="message" rows="5" cols="30" class="f-comments"></textarea><br /></label>
    <div class="f-submit-wrap">
        <input type="submit" value="Submit" class="f-submit" /><br />
    </div>
</fieldset>
</form>