<h2>Contact</h2>
<hr />
<form action="" method="post">
<fieldset>
    <legend>Contact Form</legend>
    <ul>
        <li><label for="name">Name: <input type="text" id="name" name="name" /></label></li>
        <li><label for="email">Email address: <input type="text" id="email" name="email" /></label></li>
        <li><label for="subject">Subject: <input type="text" id="subject" name="subject" /></label></li>
        <li><label for="message">Message: <textarea id="message" name="message" rows="5" cols="30"></textarea></label></li>
        <li><button type="submit">Send</button></li>
    </ul>
</fieldset>
</form>