<?php echo $this->partial('heading.phtml', array('heading' => 'Security System')); ?>
<p><a href="<?php echo $this->Url(array(), 'security_accounts_path', true); ?>">Accounts</a></p>
<p><a href="<?php echo $this->Url(array(), 'security_groups_path', true); ?>">Groups</a></p>
<p><a href="<?php echo $this->Url(array(), 'security_settings_path'); ?>">Settings</a></p>
<p><a href="<?php echo $this->Url(array('controller'=>'update'), 'default'); ?>">Update</a></p>