<table>
	<tr class="head">
		<th class="first">User</th>
		<th colspan="3">Actions</th>
	</tr>
	<?php if ($this->users && $this->users->count()): ?>
	<?php foreach($this->groups as $group): ?>
	<tr>
		<th><?php echo $group; ?></th>
		<td><a href="<?php echo $this->Url(array('id'=>current($group->identifier())), 'group_path')?>" title=""><img src="<?php echo $this->baseUrl('interface/search.png'); ?>" alt="View" /></a></td>
		<td><a href="<?php echo $this->Url(array('id'=>current($group->identifier())), 'edit_group_path')?>"><img src="<?php echo $this->baseUrl('interface/modify.png'); ?>" alt="Edit"></a></td>
		<td><a href="<?php echo $this->Url(array('id'=>current($group->identifier())), 'delete_group_path')?>"><img src="<?php echo $this->baseUrl('interface/delete.png'); ?>" alt="Delete"></a></td>
	</tr>
	<?php endforeach; ?>
	<?php else: ?>
    <tr>
        <td colspan="4">There are currently no groups in the database</td>
    </tr>
    <?php endif; ?>
	<tr class="foot">
		<td class="first" colspan="3">Add a New group</td><td><a href="<?php echo $this->Url(array(), 'new_group_path'); ?>"><img src="<?php echo $this->baseUrl('interface/add.png'); ?>" alt="+" /></a></td>
	</tr>
</table>