<?php echo $this->partial('partials/heading.phtml', array('heading' => 'Step One: Bootstrap and Options')); ?>
<?php echo $this->partial('partials/errors.phtml', array('errors' => $this->errors)); ?>
<p>The installer has determined that the security library to be in the following directory.
    Please add this to your include path:</p>
<br />
<pre>
<?php echo $this->path; ?>
</pre>
<br />
<p>Next, place the following line near the end of your bootstrap.
    Make sure it is *after* you have set up your doctrine database connection
    and configured your front controller.</p>
<br />
<pre>
Security::init();
</pre>
<br />
<p>Last, the installer needs to load options from it's included xml file.</p>
<?php echo $this->form; ?>