<?php echo $this->partial('partials/heading.phtml', array('heading' => 'Step Two: Database Privileges')); ?>
<?php echo $this->partial('partials/errors.phtml', array('errors' => $this->errors)); ?>
<p>The installer will now check that it has proper database privileges:<br />
    CREATE, INSERT, UPDATE, DELETE, and ALTER.</p>
<br />
<p>To do this, the installer will make use of it's included migration files.</p>
<?php echo $this->form; ?>