<?php echo $this->partial('partials/heading.phtml', array('heading' => 'Step Four: Add Relation')); ?>
<?php echo $this->partial('partials/errors.phtml', array('errors' => $this->errors)); ?>
<p>Please add the following to your Base<?php echo $this->class; ?> class.</p>
<pre>
public function setUp()
{
    parent::setUp();
    
    $this->hasMany('SecurityGroup as Groups', array(
        'local'     =>  '<?php echo $this->columnF; ?>',
        'foreign'   =>  'group_id',
        'refClass'  =>  'SecurityGroupAccount'));
    
    $this->hasMany('SecurityGroupAccount', array(
        'local'     =>  '<?php echo $this->columnL; ?>',
        'foreign'   =>  '<?php echo $this->columnF; ?>'));
}
</pre>
<br />
If you plan on regenerating your models at any point, add the following relation to your schema file:</p>
<pre>
relations:
  Groups:
    refClass: SecurityGroupAccount
    class: SecurityGroup
    local: <?php echo $this->columnF; ?> 
    foreign: group_id
    type: many
  SecurityGroupAccount:
    local: <?php echo $this->columnL; ?> 
    foreign: <?php echo $this->columnF; ?> 
    type: many
</pre>
<?php echo $this->form; ?>