<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta() . "\n"; ?>
<?php echo $this->headLink() . "\n"; ?>
<?php echo $this->headTitle() . "\n"; ?>
<?php echo $this->headStyle() . "\n"; ?>
<?php echo $this->headScript() . "\n"; ?>
<?php echo $this->dojo() . "\n"; ?>
</head>
<body>
<?php echo $this->inlineScript() . "\n"; ?>
    <div id="wrapper">
        <div id="header">
            <h1><a href="<?php echo $this->Url(array(), 'default', true); ?>"><?php echo $this->placeholder('branding'); ?></a></h1>
        </div>
        <div id="navigation">
            <ul>
                <li class="first"><a href="<?php echo $this->Url(array(), 'default', true); ?>">Home</a></li>
                <li><a href="<?php echo $this->Url(array('module'=>'blog'), 'default', true); ?>">Blog</a></li>
                <li><a href="<?php echo $this->Url(array('action'=>'about'), 'default', true); ?>">About</a></li>
                <li class="last"><a href="<?php echo $this->Url(array('action'=>'contact'), 'default', true); ?>">Contact</a></li>
            </ul>
        </div>          
        <div id="content">
            <div id="sidebar">
                <?php echo $this->action('index', 'sidebar', 'default') . "\n"; ?>
            </div>
            <div id="content-main">
                <?php echo $this->layout()->content . "\n"; ?>
            </div>
        </div>
        <div id="footer">       
            <p>&copy; <?php echo date('Y'); ?> <strong><?php echo $this->placeholder('branding'); ?></strong></p>      
        </div>
    </div>
</body>
</html>