<?php echo $this->partial('heading.phtml', array('heading' => 'Security Module Installer')); ?>
<p>Welcome to the security module installer.</p>
<p>Throughout this wizard, the installer will try to determine paths of different files and directories.
    Please correct them if they are wrong.</p>
<p><a href="<?php echo $this->Url(array('action'=>'step-one'), 'default'); ?>">Click here to begin</a></p>