<h2>Step Three: Model Generation</h2>
<?php if (!empty($this->errors)): ?>
<p>The following error(s) occured:</p>
<ul class="error">
<?php foreach ($this->errors as $error): ?>
    <li class="error"><?php echo $error; ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<p>Please enter the following information about your application, and verify the directories are correct.</p>
<?php echo $this->form; ?>