<?php echo $this->partial('heading.phtml', array('heading' => 'Step Four: Add Relation')); ?>
<?php echo $this->partial('errors.phtml', array('errors' => $this->errors)); ?>
<p>Please add the following to your Base<?php echo $this->class; ?> class.</p>
<pre>
$this->hasMany('SecurityGroup as Groups', array(
	'local'		=>	'<?php echo $this->column; ?>',
	'foreign'	=>	'group_id',
	'refClass'	=>	'SecurityGroupAccount'));
</pre>
<br />
If you plan on regenerating your models at any point, add the following relation to your schema file:</p>
<pre>
relations:
    SecurityGroup:
        class: SecurityGroup as Groups
        local: <?php echo $this->column; ?> 
        foreign: group_id
        refClass: SecurityGroupAccount
        type: many
</pre>
<?php echo $this->form; ?>